package com.interest.ids.common.project.bean.alarm;

public class WorkFlowProcessM {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_workflow_process_t.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_workflow_process_t.proc_id
     *
     * @mbggenerated
     */
    private String procId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_workflow_process_t.proc_state
     *
     * @mbggenerated
     */
    private String procState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_workflow_process_t.busi_state
     *
     * @mbggenerated
     */
    private String busiState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_workflow_process_t.start_time
     *
     * @mbggenerated
     */
    private Long startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_workflow_process_t.end_time
     *
     * @mbggenerated
     */
    private Long endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_workflow_process_t.update_time
     *
     * @mbggenerated
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_workflow_process_t.proc_ins_id
     *
     * @mbggenerated
     */
    private String procInsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_workflow_process_t.proc_name
     *
     * @mbggenerated
     */
    private String procName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_workflow_process_t.proc_desc
     *
     * @mbggenerated
     */
    private String procDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_workflow_process_t.current_task_id
     *
     * @mbggenerated
     */
    private String currentTaskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_workflow_process_t.currentTaskAssignee
     *
     * @mbggenerated
     */
    private String currentTaskAssignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_workflow_process_t.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_workflow_process_t.station_code
     *
     * @mbggenerated
     */
    private String stationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_workflow_process_t.enterprise_id
     *
     * @mbggenerated
     */
    private Long enterpriseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_workflow_process_t.id
     *
     * @return the value of ids_workflow_process_t.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_workflow_process_t.id
     *
     * @param id the value for ids_workflow_process_t.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_workflow_process_t.proc_id
     *
     * @return the value of ids_workflow_process_t.proc_id
     *
     * @mbggenerated
     */
    public String getProcId() {
        return procId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_workflow_process_t.proc_id
     *
     * @param procId the value for ids_workflow_process_t.proc_id
     *
     * @mbggenerated
     */
    public void setProcId(String procId) {
        this.procId = procId == null ? null : procId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_workflow_process_t.proc_state
     *
     * @return the value of ids_workflow_process_t.proc_state
     *
     * @mbggenerated
     */
    public String getProcState() {
        return procState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_workflow_process_t.proc_state
     *
     * @param procState the value for ids_workflow_process_t.proc_state
     *
     * @mbggenerated
     */
    public void setProcState(String procState) {
        this.procState = procState == null ? null : procState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_workflow_process_t.busi_state
     *
     * @return the value of ids_workflow_process_t.busi_state
     *
     * @mbggenerated
     */
    public String getBusiState() {
        return busiState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_workflow_process_t.busi_state
     *
     * @param busiState the value for ids_workflow_process_t.busi_state
     *
     * @mbggenerated
     */
    public void setBusiState(String busiState) {
        this.busiState = busiState == null ? null : busiState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_workflow_process_t.start_time
     *
     * @return the value of ids_workflow_process_t.start_time
     *
     * @mbggenerated
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_workflow_process_t.start_time
     *
     * @param startTime the value for ids_workflow_process_t.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_workflow_process_t.end_time
     *
     * @return the value of ids_workflow_process_t.end_time
     *
     * @mbggenerated
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_workflow_process_t.end_time
     *
     * @param endTime the value for ids_workflow_process_t.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_workflow_process_t.update_time
     *
     * @return the value of ids_workflow_process_t.update_time
     *
     * @mbggenerated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_workflow_process_t.update_time
     *
     * @param updateTime the value for ids_workflow_process_t.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_workflow_process_t.proc_ins_id
     *
     * @return the value of ids_workflow_process_t.proc_ins_id
     *
     * @mbggenerated
     */
    public String getProcInsId() {
        return procInsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_workflow_process_t.proc_ins_id
     *
     * @param procInsId the value for ids_workflow_process_t.proc_ins_id
     *
     * @mbggenerated
     */
    public void setProcInsId(String procInsId) {
        this.procInsId = procInsId == null ? null : procInsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_workflow_process_t.proc_name
     *
     * @return the value of ids_workflow_process_t.proc_name
     *
     * @mbggenerated
     */
    public String getProcName() {
        return procName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_workflow_process_t.proc_name
     *
     * @param procName the value for ids_workflow_process_t.proc_name
     *
     * @mbggenerated
     */
    public void setProcName(String procName) {
        this.procName = procName == null ? null : procName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_workflow_process_t.proc_desc
     *
     * @return the value of ids_workflow_process_t.proc_desc
     *
     * @mbggenerated
     */
    public String getProcDesc() {
        return procDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_workflow_process_t.proc_desc
     *
     * @param procDesc the value for ids_workflow_process_t.proc_desc
     *
     * @mbggenerated
     */
    public void setProcDesc(String procDesc) {
        this.procDesc = procDesc == null ? null : procDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_workflow_process_t.current_task_id
     *
     * @return the value of ids_workflow_process_t.current_task_id
     *
     * @mbggenerated
     */
    public String getCurrentTaskId() {
        return currentTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_workflow_process_t.current_task_id
     *
     * @param currentTaskId the value for ids_workflow_process_t.current_task_id
     *
     * @mbggenerated
     */
    public void setCurrentTaskId(String currentTaskId) {
        this.currentTaskId = currentTaskId == null ? null : currentTaskId.trim();
    }

    
    public String getCurrentTaskAssignee() {
		return currentTaskAssignee;
	}

	public void setCurrentTaskAssignee(String currentTaskAssignee) {
		this.currentTaskAssignee = currentTaskAssignee;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_workflow_process_t.create_user
     *
     * @return the value of ids_workflow_process_t.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_workflow_process_t.create_user
     *
     * @param createUser the value for ids_workflow_process_t.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_workflow_process_t.station_code
     *
     * @return the value of ids_workflow_process_t.station_code
     *
     * @mbggenerated
     */
    public String getStationCode() {
        return stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_workflow_process_t.station_code
     *
     * @param stationCode the value for ids_workflow_process_t.station_code
     *
     * @mbggenerated
     */
    public void setStationCode(String stationCode) {
        this.stationCode = stationCode == null ? null : stationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_workflow_process_t.enterprise_id
     *
     * @return the value of ids_workflow_process_t.enterprise_id
     *
     * @mbggenerated
     */
    public Long getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_workflow_process_t.enterprise_id
     *
     * @param enterpriseId the value for ids_workflow_process_t.enterprise_id
     *
     * @mbggenerated
     */
    public void setEnterpriseId(Long enterpriseId) {
        this.enterpriseId = enterpriseId;
    }
}