package com.interest.ids.biz.authorize.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DomainInfoDto implements Serializable 
{
    private static final long serialVersionUID = 1L;
    
    /**
     * 查询类型（D: 区域，E:企业）
     */
    private String model;
    /**电站编码 */
    private String stationCode;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_domain_t.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_domain_t.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_domain_t.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_domain_t.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_domain_t.enterprise_id
     *
     * @mbggenerated
     */
    private Long enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_domain_t.longitude
     *
     * @mbggenerated
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_domain_t.latitude
     *
     * @mbggenerated
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_domain_t.radius
     *
     * @mbggenerated
     */
    private BigDecimal radius;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_domain_t.domain_price
     *
     * @mbggenerated
     */
    private BigDecimal domainPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_domain_t.currency
     *
     * @mbggenerated
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_domain_t.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_domain_t.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_domain_t.modify_user_id
     *
     * @mbggenerated
     */
    private Long modifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_domain_t.modify_date
     *
     * @mbggenerated
     */
    private String path;
    
    public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	private Date modifyDate;

    public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getStationCode() {
        return stationCode;
    }

    public void setStationCode(String stationCode) {
        this.stationCode = stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_domain_t.id
     *
     * @return the value of ids_sm_domain_t.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_domain_t.id
     *
     * @param id the value for ids_sm_domain_t.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_domain_t.name
     *
     * @return the value of ids_sm_domain_t.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_domain_t.name
     *
     * @param name the value for ids_sm_domain_t.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_domain_t.description
     *
     * @return the value of ids_sm_domain_t.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_domain_t.description
     *
     * @param description the value for ids_sm_domain_t.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_domain_t.parent_id
     *
     * @return the value of ids_sm_domain_t.parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_domain_t.parent_id
     *
     * @param parentId the value for ids_sm_domain_t.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_domain_t.enterprise_id
     *
     * @return the value of ids_sm_domain_t.enterprise_id
     *
     * @mbggenerated
     */
    public Long getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_domain_t.enterprise_id
     *
     * @param enterpriseId the value for ids_sm_domain_t.enterprise_id
     *
     * @mbggenerated
     */
    public void setEnterpriseId(Long enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_domain_t.longitude
     *
     * @return the value of ids_sm_domain_t.longitude
     *
     * @mbggenerated
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_domain_t.longitude
     *
     * @param longitude the value for ids_sm_domain_t.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_domain_t.latitude
     *
     * @return the value of ids_sm_domain_t.latitude
     *
     * @mbggenerated
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_domain_t.latitude
     *
     * @param latitude the value for ids_sm_domain_t.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_domain_t.radius
     *
     * @return the value of ids_sm_domain_t.radius
     *
     * @mbggenerated
     */
    public BigDecimal getRadius() {
        return radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_domain_t.radius
     *
     * @param radius the value for ids_sm_domain_t.radius
     *
     * @mbggenerated
     */
    public void setRadius(BigDecimal radius) {
        this.radius = radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_domain_t.domain_price
     *
     * @return the value of ids_sm_domain_t.domain_price
     *
     * @mbggenerated
     */
    public BigDecimal getDomainPrice() {
        return domainPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_domain_t.domain_price
     *
     * @param domainPrice the value for ids_sm_domain_t.domain_price
     *
     * @mbggenerated
     */
    public void setDomainPrice(BigDecimal domainPrice) {
        this.domainPrice = domainPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_domain_t.currency
     *
     * @return the value of ids_sm_domain_t.currency
     *
     * @mbggenerated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_domain_t.currency
     *
     * @param currency the value for ids_sm_domain_t.currency
     *
     * @mbggenerated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_domain_t.create_user_id
     *
     * @return the value of ids_sm_domain_t.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_domain_t.create_user_id
     *
     * @param createUserId the value for ids_sm_domain_t.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_domain_t.create_date
     *
     * @return the value of ids_sm_domain_t.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_domain_t.create_date
     *
     * @param createDate the value for ids_sm_domain_t.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_domain_t.modify_user_id
     *
     * @return the value of ids_sm_domain_t.modify_user_id
     *
     * @mbggenerated
     */
    public Long getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_domain_t.modify_user_id
     *
     * @param modifyUserId the value for ids_sm_domain_t.modify_user_id
     *
     * @mbggenerated
     */
    public void setModifyUserId(Long modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_domain_t.modify_date
     *
     * @return the value of ids_sm_domain_t.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_domain_t.modify_date
     *
     * @param modifyDate the value for ids_sm_domain_t.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}
