package com.interest.ids.biz.authorize.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.interest.ids.common.project.bean.sm.AuthorizeM;

public class RoleInfoDto implements Serializable
{
    private static final long serialVersionUID = 1L;
    /**
     * 角色对应的权限
     */
    private List<AuthorizeM> authorizeMs;
    /**权限id*/
    private String authIds;

    /**用户id */
    private Long userId;
    
    /**
     * 查询起始/结束时间
     */
    private Long startTime;
    private Long endTime;
    /**
     * 分页的数据 分别是 页数 和 每页显示条数 start
     */
    private Integer index;
    private Integer pageSize;
    /** 
     * 分页的数据 分别是 页数 和 每页显示条数 end
     */
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_role_info_t.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_role_info_t.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_role_info_t.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_role_info_t.role_type
     *
     * @mbggenerated
     */
    private String roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_role_info_t.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_role_info_t.enterprise_id
     *
     * @mbggenerated
     */
    private Long enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_role_info_t.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_role_info_t.create_date
     *
     * @mbggenerated
     */
    private Date createDate;
    
    private Long createDateLong;

    public Long getStartTime() {
		return startTime;
	}

	public void setStartTime(Long startTime) {
		this.startTime = startTime;
	}

	public Long getEndTime() {
		return endTime;
	}

	public void setEndTime(Long endTime) {
		this.endTime = endTime;
	}

	public List<AuthorizeM> getAuthorizeMs() {
        return authorizeMs;
    }

    public void setAuthorizeMs(List<AuthorizeM> authorizeMs) {
        this.authorizeMs = authorizeMs;
    }

    public Long getCreateDateLong() {
        return createDateLong;
    }

    public void setCreateDateLong(Long createDateLong)
    {   if(null != createDateLong)
        {
            this.setCreateDate(new Date(createDateLong));
        }
        this.createDateLong = createDateLong;
    }

    public Integer getIndex() {
        return index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    public Integer getPageSize() {
        return pageSize;
    }

    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_role_info_t.modify_user_id
     *
     * @mbggenerated
     */
    private Long modifyUserId;

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_role_info_t.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    public String getAuthIds() {
        return authIds;
    }

    public void setAuthIds(String authIds) {
        this.authIds = authIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_role_info_t.id
     *
     * @return the value of ids_sm_role_info_t.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_role_info_t.id
     *
     * @param id the value for ids_sm_role_info_t.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_role_info_t.name
     *
     * @return the value of ids_sm_role_info_t.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_role_info_t.name
     *
     * @param name the value for ids_sm_role_info_t.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_role_info_t.description
     *
     * @return the value of ids_sm_role_info_t.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_role_info_t.description
     *
     * @param description the value for ids_sm_role_info_t.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_role_info_t.role_type
     *
     * @return the value of ids_sm_role_info_t.role_type
     *
     * @mbggenerated
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_role_info_t.role_type
     *
     * @param roleType the value for ids_sm_role_info_t.role_type
     *
     * @mbggenerated
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType == null ? null : roleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_role_info_t.status
     *
     * @return the value of ids_sm_role_info_t.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_role_info_t.status
     *
     * @param status the value for ids_sm_role_info_t.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_role_info_t.enterprise_id
     *
     * @return the value of ids_sm_role_info_t.enterprise_id
     *
     * @mbggenerated
     */
    public Long getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_role_info_t.enterprise_id
     *
     * @param enterpriseId the value for ids_sm_role_info_t.enterprise_id
     *
     * @mbggenerated
     */
    public void setEnterpriseId(Long enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_role_info_t.create_user_id
     *
     * @return the value of ids_sm_role_info_t.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_role_info_t.create_user_id
     *
     * @param createUserId the value for ids_sm_role_info_t.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_role_info_t.create_date
     *
     * @return the value of ids_sm_role_info_t.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_role_info_t.create_date
     *
     * @param createDate the value for ids_sm_role_info_t.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        if(createDate!=null)
        {
            this.createDateLong = createDate.getTime();
        }
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_role_info_t.modify_user_id
     *
     * @return the value of ids_sm_role_info_t.modify_user_id
     *
     * @mbggenerated
     */
    public Long getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_role_info_t.modify_user_id
     *
     * @param modifyUserId the value for ids_sm_role_info_t.modify_user_id
     *
     * @mbggenerated
     */
    public void setModifyUserId(Long modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_role_info_t.modify_date
     *
     * @return the value of ids_sm_role_info_t.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_role_info_t.modify_date
     *
     * @param modifyDate the value for ids_sm_role_info_t.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}
