package com.interest.ids.common.project.bean.sm;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class EnterpriseInfo implements Serializable
{
    private static final long serialVersionUID = -4662732510831404051L;

    //企业下所有的站点
	private List<StationInfoM> stations;
	
    public List<StationInfoM> getStations() {
		return stations;
	}

	public void setStations(List<StationInfoM> stations) {
		this.stations = stations;
	}

	private Double longitude;
	private Double latitude;
	private Double radius;
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_enterprise_t.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_enterprise_t.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_enterprise_t.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_enterprise_t.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_enterprise_t.avatar_path
     *
     * @mbggenerated
     */
    private String avatarPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_enterprise_t.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_enterprise_t.contact_people
     *
     * @mbggenerated
     */
    private String contactPeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_enterprise_t.contact_phone
     *
     * @mbggenerated
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_enterprise_t.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_enterprise_t.device_limit
     *
     * @mbggenerated
     */
    private Integer deviceLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_enterprise_t.user_limit
     *
     * @mbggenerated
     */
    private Integer userLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_enterprise_t.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_enterprise_t.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_enterprise_t.modify_user_id
     *
     * @mbggenerated
     */
    private Long modifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_enterprise_t.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_enterprise_t.id
     *
     * @return the value of ids_sm_enterprise_t.id
     *
     * @mbggenerated
     */
    // 企业LOGO的fileId
    private String logo;
    
    public Long getId() {
        return id;
    }

    public Double getLongitude() {
		return longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getRadius() {
		return radius;
	}

	public void setRadius(Double radius) {
		this.radius = radius;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_enterprise_t.id
     *
     * @param id the value for ids_sm_enterprise_t.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_enterprise_t.name
     *
     * @return the value of ids_sm_enterprise_t.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_enterprise_t.name
     *
     * @param name the value for ids_sm_enterprise_t.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_enterprise_t.description
     *
     * @return the value of ids_sm_enterprise_t.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_enterprise_t.description
     *
     * @param description the value for ids_sm_enterprise_t.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_enterprise_t.parent_id
     *
     * @return the value of ids_sm_enterprise_t.parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_enterprise_t.parent_id
     *
     * @param parentId the value for ids_sm_enterprise_t.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_enterprise_t.avatar_path
     *
     * @return the value of ids_sm_enterprise_t.avatar_path
     *
     * @mbggenerated
     */
    public String getAvatarPath() {
        return avatarPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_enterprise_t.avatar_path
     *
     * @param avatarPath the value for ids_sm_enterprise_t.avatar_path
     *
     * @mbggenerated
     */
    public void setAvatarPath(String avatarPath) {
        this.avatarPath = avatarPath == null ? null : avatarPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_enterprise_t.address
     *
     * @return the value of ids_sm_enterprise_t.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_enterprise_t.address
     *
     * @param address the value for ids_sm_enterprise_t.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_enterprise_t.contact_people
     *
     * @return the value of ids_sm_enterprise_t.contact_people
     *
     * @mbggenerated
     */
    public String getContactPeople() {
        return contactPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_enterprise_t.contact_people
     *
     * @param contactPeople the value for ids_sm_enterprise_t.contact_people
     *
     * @mbggenerated
     */
    public void setContactPeople(String contactPeople) {
        this.contactPeople = contactPeople == null ? null : contactPeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_enterprise_t.contact_phone
     *
     * @return the value of ids_sm_enterprise_t.contact_phone
     *
     * @mbggenerated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_enterprise_t.contact_phone
     *
     * @param contactPhone the value for ids_sm_enterprise_t.contact_phone
     *
     * @mbggenerated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_enterprise_t.email
     *
     * @return the value of ids_sm_enterprise_t.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_enterprise_t.email
     *
     * @param email the value for ids_sm_enterprise_t.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_enterprise_t.device_limit
     *
     * @return the value of ids_sm_enterprise_t.device_limit
     *
     * @mbggenerated
     */
    public Integer getDeviceLimit() {
        return deviceLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_enterprise_t.device_limit
     *
     * @param deviceLimit the value for ids_sm_enterprise_t.device_limit
     *
     * @mbggenerated
     */
    public void setDeviceLimit(Integer deviceLimit) {
        this.deviceLimit = deviceLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_enterprise_t.user_limit
     *
     * @return the value of ids_sm_enterprise_t.user_limit
     *
     * @mbggenerated
     */
    public Integer getUserLimit() {
        return userLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_enterprise_t.user_limit
     *
     * @param userLimit the value for ids_sm_enterprise_t.user_limit
     *
     * @mbggenerated
     */
    public void setUserLimit(Integer userLimit) {
        this.userLimit = userLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_enterprise_t.create_user_id
     *
     * @return the value of ids_sm_enterprise_t.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_enterprise_t.create_user_id
     *
     * @param createUserId the value for ids_sm_enterprise_t.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_enterprise_t.create_date
     *
     * @return the value of ids_sm_enterprise_t.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_enterprise_t.create_date
     *
     * @param createDate the value for ids_sm_enterprise_t.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_enterprise_t.modify_user_id
     *
     * @return the value of ids_sm_enterprise_t.modify_user_id
     *
     * @mbggenerated
     */
    public Long getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_enterprise_t.modify_user_id
     *
     * @param modifyUserId the value for ids_sm_enterprise_t.modify_user_id
     *
     * @mbggenerated
     */
    public void setModifyUserId(Long modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_enterprise_t.modify_date
     *
     * @return the value of ids_sm_enterprise_t.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_enterprise_t.modify_date
     *
     * @param modifyDate the value for ids_sm_enterprise_t.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

	public String getLogo() {
		return logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}
    
    
}