package com.interest.ids.common.project.bean.sm;

import java.io.Serializable;

public class ResourceM implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_resource_t.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_resource_t.resource_key
     *
     * @mbggenerated
     */
    private String resourceKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_resource_t.auth_id
     *
     * @mbggenerated
     */
    private Long authId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_resource_t.resource_name
     *
     * @mbggenerated
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_resource_t.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_resource_t.auth_url
     *
     * @mbggenerated
     */
    private String authUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_resource_t.request_type
     *
     * @mbggenerated
     */
    private String requestType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_resource_t.id
     *
     * @return the value of ids_sm_resource_t.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_resource_t.id
     *
     * @param id the value for ids_sm_resource_t.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_resource_t.resource_key
     *
     * @return the value of ids_sm_resource_t.resource_key
     *
     * @mbggenerated
     */
    public String getResourceKey() {
        return resourceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_resource_t.resource_key
     *
     * @param resourceKey the value for ids_sm_resource_t.resource_key
     *
     * @mbggenerated
     */
    public void setResourceKey(String resourceKey) {
        this.resourceKey = resourceKey == null ? null : resourceKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_resource_t.auth_id
     *
     * @return the value of ids_sm_resource_t.auth_id
     *
     * @mbggenerated
     */
    public Long getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_resource_t.auth_id
     *
     * @param authId the value for ids_sm_resource_t.auth_id
     *
     * @mbggenerated
     */
    public void setAuthId(Long authId) {
        this.authId = authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_resource_t.resource_name
     *
     * @return the value of ids_sm_resource_t.resource_name
     *
     * @mbggenerated
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_resource_t.resource_name
     *
     * @param resourceName the value for ids_sm_resource_t.resource_name
     *
     * @mbggenerated
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_resource_t.description
     *
     * @return the value of ids_sm_resource_t.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_resource_t.description
     *
     * @param description the value for ids_sm_resource_t.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_resource_t.auth_url
     *
     * @return the value of ids_sm_resource_t.auth_url
     *
     * @mbggenerated
     */
    public String getAuthUrl() {
        return authUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_resource_t.auth_url
     *
     * @param authUrl the value for ids_sm_resource_t.auth_url
     *
     * @mbggenerated
     */
    public void setAuthUrl(String authUrl) {
        this.authUrl = authUrl == null ? null : authUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_resource_t.request_type
     *
     * @return the value of ids_sm_resource_t.request_type
     *
     * @mbggenerated
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_resource_t.request_type
     *
     * @param requestType the value for ids_sm_resource_t.request_type
     *
     * @mbggenerated
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType == null ? null : requestType.trim();
    }
}