package com.interest.ids.common.project.bean.sm;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserInfo implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	//用户角色关系
	private List<RoleInfo> roles = new ArrayList<RoleInfo>();
	//用户权限关系
	private List<AuthorizeM> authorizeMs = new ArrayList<AuthorizeM>();
	
	//用户和企业之间的关系
	private EnterpriseInfo enterprise = null;
	
	//用户资源
	private List<ResourceM> resources;
	
	public List<ResourceM> getResources() {
		return resources;
	}

	public void setResources(List<ResourceM> resources) {
		this.resources = resources;
	}

	public EnterpriseInfo getEnterprise() {
		return enterprise;
	}

	public void setEnterprise(EnterpriseInfo enterprise) {
		this.enterprise = enterprise;
	}

	public List<AuthorizeM> getAuthorizeMs() {
		return authorizeMs;
	}

	public void setAuthorizeMs(List<AuthorizeM> authorizeMs) {
		this.authorizeMs = authorizeMs;
	}

	public List<RoleInfo> getRoles() {
		return roles;
	}

	public void setRoles(List<RoleInfo> roles) {
		this.roles = roles;
	}
	
	private String type_;

	public String getType_() {
		return type_;
	}

	public void setType_(String type_) {
		this.type_ = type_;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_user_info_t.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_user_info_t.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_user_info_t.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_user_info_t.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_user_info_t.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_user_info_t.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_user_info_t.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_user_info_t.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_user_info_t.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_user_info_t.user_type
     *
     * @mbggenerated
     */
    private Byte userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_user_info_t.enterprise_id
     *
     * @mbggenerated
     */
    private Long enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_user_info_t.create_user_id
     *
     * @mbggenerated
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_user_info_t.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_user_info_t.modify_user_id
     *
     * @mbggenerated
     */
    private Long modifyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_sm_user_info_t.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_user_info_t.id
     *
     * @return the value of ids_sm_user_info_t.id
     *
     * @mbggenerated
     */
	public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_user_info_t.id
     *
     * @param id the value for ids_sm_user_info_t.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_user_info_t.login_name
     *
     * @return the value of ids_sm_user_info_t.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_user_info_t.login_name
     *
     * @param loginName the value for ids_sm_user_info_t.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_user_info_t.password
     *
     * @return the value of ids_sm_user_info_t.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_user_info_t.password
     *
     * @param password the value for ids_sm_user_info_t.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_user_info_t.user_name
     *
     * @return the value of ids_sm_user_info_t.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_user_info_t.user_name
     *
     * @param userName the value for ids_sm_user_info_t.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_user_info_t.qq
     *
     * @return the value of ids_sm_user_info_t.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_user_info_t.qq
     *
     * @param qq the value for ids_sm_user_info_t.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_user_info_t.email
     *
     * @return the value of ids_sm_user_info_t.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_user_info_t.email
     *
     * @param email the value for ids_sm_user_info_t.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_user_info_t.gender
     *
     * @return the value of ids_sm_user_info_t.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_user_info_t.gender
     *
     * @param gender the value for ids_sm_user_info_t.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_user_info_t.phone
     *
     * @return the value of ids_sm_user_info_t.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_user_info_t.phone
     *
     * @param phone the value for ids_sm_user_info_t.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_user_info_t.status
     *
     * @return the value of ids_sm_user_info_t.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_user_info_t.status
     *
     * @param status the value for ids_sm_user_info_t.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_user_info_t.user_type
     *
     * @return the value of ids_sm_user_info_t.user_type
     *
     * @mbggenerated
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_user_info_t.user_type
     *
     * @param userType the value for ids_sm_user_info_t.user_type
     *
     * @mbggenerated
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_user_info_t.enterprise_id
     *
     * @return the value of ids_sm_user_info_t.enterprise_id
     *
     * @mbggenerated
     */
    public Long getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_user_info_t.enterprise_id
     *
     * @param enterpriseId the value for ids_sm_user_info_t.enterprise_id
     *
     * @mbggenerated
     */
    public void setEnterpriseId(Long enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_user_info_t.create_user_id
     *
     * @return the value of ids_sm_user_info_t.create_user_id
     *
     * @mbggenerated
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_user_info_t.create_user_id
     *
     * @param createUserId the value for ids_sm_user_info_t.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_user_info_t.create_date
     *
     * @return the value of ids_sm_user_info_t.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_user_info_t.create_date
     *
     * @param createDate the value for ids_sm_user_info_t.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_user_info_t.modify_user_id
     *
     * @return the value of ids_sm_user_info_t.modify_user_id
     *
     * @mbggenerated
     */
    public Long getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_user_info_t.modify_user_id
     *
     * @param modifyUserId the value for ids_sm_user_info_t.modify_user_id
     *
     * @mbggenerated
     */
    public void setModifyUserId(Long modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_sm_user_info_t.modify_date
     *
     * @return the value of ids_sm_user_info_t.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_sm_user_info_t.modify_date
     *
     * @param modifyDate the value for ids_sm_user_info_t.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}