const SET_ROLE = 'SET_ROLE'
const SET_PERMISSION_ROUTES = 'SET_PERMISSION_ROUTES'
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
const RESOURCES = 'RESOURCES'
// 显示图片LOGO的路径
const LOGO_IMG_PATH = 'LOG_IMG_PATH';
const SET_LANG = 'SET_LANG' // 设置当前的语言

export {
  SET_ROLE,
  SET_PERMISSION_ROUTES,
  TOGGLE_SIDEBAR,
  RESOURCES,
  LOGO_IMG_PATH,
  SET_LANG
}
