package com.interest.ids.common.project.bean.device;

import com.interest.ids.common.project.bean.BaseBean;

public class ModelVersionInfoM extends BaseBean{

    private static final long serialVersionUID = 1770375639334845972L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.parent_model_version_code
     *
     * @mbggenerated
     */
    private String parentModelVersionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.model_version_code
     *
     * @mbggenerated
     */
    private String modelVersionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.enterprise_id
     *
     * @mbggenerated
     */
    private Long enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.device_type_id
     *
     * @mbggenerated
     */
    private Integer deviceTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.vender_name
     *
     * @mbggenerated
     */
    private String venderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.protocol_code
     *
     * @mbggenerated
     */
    private String protocolCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.model_code
     *
     * @mbggenerated
     */
    private String modelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.model_version
     *
     * @mbggenerated
     */
    private String modelVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.file_version
     *
     * @mbggenerated
     */
    private String fileVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.is_multipurpose
     *
     * @mbggenerated
     */
    private Byte isMultipurpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.data_model_name
     *
     * @mbggenerated
     */
    private String dataModelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.yc_alarm_flag
     *
     * @mbggenerated
     */
    private Boolean ycAlarmFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.alarm_flag_addr
     *
     * @mbggenerated
     */
    private Integer alarmFlagAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.ava_flag_vals
     *
     * @mbggenerated
     */
    private String avaFlagVals;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.data_table_name
     *
     * @mbggenerated
     */
    private String dataTableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.data_model_table_name
     *
     * @mbggenerated
     */
    private String dataModelTableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.create_date
     *
     * @mbggenerated
     */
    private Long createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.update_date
     *
     * @mbggenerated
     */
    private Long updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_model_version_info_t.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.id
     *
     * @return the value of ids_model_version_info_t.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.id
     *
     * @param id the value for ids_model_version_info_t.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.parent_model_version_code
     *
     * @return the value of ids_model_version_info_t.parent_model_version_code
     *
     * @mbggenerated
     */
    public String getParentModelVersionCode() {
        return parentModelVersionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.parent_model_version_code
     *
     * @param parentModelVersionCode the value for ids_model_version_info_t.parent_model_version_code
     *
     * @mbggenerated
     */
    public void setParentModelVersionCode(String parentModelVersionCode) {
        this.parentModelVersionCode = parentModelVersionCode == null ? null : parentModelVersionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.model_version_code
     *
     * @return the value of ids_model_version_info_t.model_version_code
     *
     * @mbggenerated
     */
    public String getModelVersionCode() {
        return modelVersionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.model_version_code
     *
     * @param modelVersionCode the value for ids_model_version_info_t.model_version_code
     *
     * @mbggenerated
     */
    public void setModelVersionCode(String modelVersionCode) {
        this.modelVersionCode = modelVersionCode == null ? null : modelVersionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.enterprise_id
     *
     * @return the value of ids_model_version_info_t.enterprise_id
     *
     * @mbggenerated
     */
    public Long getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.enterprise_id
     *
     * @param enterpriseId the value for ids_model_version_info_t.enterprise_id
     *
     * @mbggenerated
     */
    public void setEnterpriseId(Long enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.device_type_id
     *
     * @return the value of ids_model_version_info_t.device_type_id
     *
     * @mbggenerated
     */
    public Integer getDeviceTypeId() {
        return deviceTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.device_type_id
     *
     * @param deviceTypeId the value for ids_model_version_info_t.device_type_id
     *
     * @mbggenerated
     */
    public void setDeviceTypeId(Integer deviceTypeId) {
        this.deviceTypeId = deviceTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.vender_name
     *
     * @return the value of ids_model_version_info_t.vender_name
     *
     * @mbggenerated
     */
    public String getVenderName() {
        return venderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.vender_name
     *
     * @param venderName the value for ids_model_version_info_t.vender_name
     *
     * @mbggenerated
     */
    public void setVenderName(String venderName) {
        this.venderName = venderName == null ? null : venderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.protocol_code
     *
     * @return the value of ids_model_version_info_t.protocol_code
     *
     * @mbggenerated
     */
    public String getProtocolCode() {
        return protocolCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.protocol_code
     *
     * @param protocolCode the value for ids_model_version_info_t.protocol_code
     *
     * @mbggenerated
     */
    public void setProtocolCode(String protocolCode) {
        this.protocolCode = protocolCode == null ? null : protocolCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.model_code
     *
     * @return the value of ids_model_version_info_t.model_code
     *
     * @mbggenerated
     */
    public String getModelCode() {
        return modelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.model_code
     *
     * @param modelCode the value for ids_model_version_info_t.model_code
     *
     * @mbggenerated
     */
    public void setModelCode(String modelCode) {
        this.modelCode = modelCode == null ? null : modelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.model_version
     *
     * @return the value of ids_model_version_info_t.model_version
     *
     * @mbggenerated
     */
    public String getModelVersion() {
        return modelVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.model_version
     *
     * @param modelVersion the value for ids_model_version_info_t.model_version
     *
     * @mbggenerated
     */
    public void setModelVersion(String modelVersion) {
        this.modelVersion = modelVersion == null ? null : modelVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.file_version
     *
     * @return the value of ids_model_version_info_t.file_version
     *
     * @mbggenerated
     */
    public String getFileVersion() {
        return fileVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.file_version
     *
     * @param fileVersion the value for ids_model_version_info_t.file_version
     *
     * @mbggenerated
     */
    public void setFileVersion(String fileVersion) {
        this.fileVersion = fileVersion == null ? null : fileVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.is_multipurpose
     *
     * @return the value of ids_model_version_info_t.is_multipurpose
     *
     * @mbggenerated
     */
    public Byte getIsMultipurpose() {
        return isMultipurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.is_multipurpose
     *
     * @param isMultipurpose the value for ids_model_version_info_t.is_multipurpose
     *
     * @mbggenerated
     */
    public void setIsMultipurpose(Byte isMultipurpose) {
        this.isMultipurpose = isMultipurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.data_model_name
     *
     * @return the value of ids_model_version_info_t.data_model_name
     *
     * @mbggenerated
     */
    public String getDataModelName() {
        return dataModelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.data_model_name
     *
     * @param dataModelName the value for ids_model_version_info_t.data_model_name
     *
     * @mbggenerated
     */
    public void setDataModelName(String dataModelName) {
        this.dataModelName = dataModelName == null ? null : dataModelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.yc_alarm_flag
     *
     * @return the value of ids_model_version_info_t.yc_alarm_flag
     *
     * @mbggenerated
     */
    public Boolean getYcAlarmFlag() {
        return ycAlarmFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.yc_alarm_flag
     *
     * @param ycAlarmFlag the value for ids_model_version_info_t.yc_alarm_flag
     *
     * @mbggenerated
     */
    public void setYcAlarmFlag(Boolean ycAlarmFlag) {
        this.ycAlarmFlag = ycAlarmFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.alarm_flag_addr
     *
     * @return the value of ids_model_version_info_t.alarm_flag_addr
     *
     * @mbggenerated
     */
    public Integer getAlarmFlagAddr() {
        return alarmFlagAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.alarm_flag_addr
     *
     * @param alarmFlagAddr the value for ids_model_version_info_t.alarm_flag_addr
     *
     * @mbggenerated
     */
    public void setAlarmFlagAddr(Integer alarmFlagAddr) {
        this.alarmFlagAddr = alarmFlagAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.ava_flag_vals
     *
     * @return the value of ids_model_version_info_t.ava_flag_vals
     *
     * @mbggenerated
     */
    public String getAvaFlagVals() {
        return avaFlagVals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.ava_flag_vals
     *
     * @param avaFlagVals the value for ids_model_version_info_t.ava_flag_vals
     *
     * @mbggenerated
     */
    public void setAvaFlagVals(String avaFlagVals) {
        this.avaFlagVals = avaFlagVals == null ? null : avaFlagVals.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.data_table_name
     *
     * @return the value of ids_model_version_info_t.data_table_name
     *
     * @mbggenerated
     */
    public String getDataTableName() {
        return dataTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.data_table_name
     *
     * @param dataTableName the value for ids_model_version_info_t.data_table_name
     *
     * @mbggenerated
     */
    public void setDataTableName(String dataTableName) {
        this.dataTableName = dataTableName == null ? null : dataTableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.data_model_table_name
     *
     * @return the value of ids_model_version_info_t.data_model_table_name
     *
     * @mbggenerated
     */
    public String getDataModelTableName() {
        return dataModelTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.data_model_table_name
     *
     * @param dataModelTableName the value for ids_model_version_info_t.data_model_table_name
     *
     * @mbggenerated
     */
    public void setDataModelTableName(String dataModelTableName) {
        this.dataModelTableName = dataModelTableName == null ? null : dataModelTableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.create_date
     *
     * @return the value of ids_model_version_info_t.create_date
     *
     * @mbggenerated
     */
    public Long getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.create_date
     *
     * @param createDate the value for ids_model_version_info_t.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.create_user
     *
     * @return the value of ids_model_version_info_t.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.create_user
     *
     * @param createUser the value for ids_model_version_info_t.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.update_date
     *
     * @return the value of ids_model_version_info_t.update_date
     *
     * @mbggenerated
     */
    public Long getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.update_date
     *
     * @param updateDate the value for ids_model_version_info_t.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Long updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_model_version_info_t.update_user
     *
     * @return the value of ids_model_version_info_t.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_model_version_info_t.update_user
     *
     * @param updateUser the value for ids_model_version_info_t.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}