package com.interest.ids.common.project.bean.device;

import com.interest.ids.common.project.bean.BaseBean;

import java.util.Date;

public class TeleSignalM extends BaseBean{

    private static final long serialVersionUID = 3867967319723225050L;

    private String stationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.station_name
     *
     * @mbggenerated
     */
    private String stationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.busi_code
     *
     * @mbggenerated
     */
    private String busiCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.busi_name
     *
     * @mbggenerated
     */
    private String busiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.device_type_id
     *
     * @mbggenerated
     */
    private Short deviceTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.device_id
     *
     * @mbggenerated
     */
    private Long deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.status_id
     *
     * @mbggenerated
     */
    private Byte statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.act_id
     *
     * @mbggenerated
     */
    private Byte actId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.raised_date
     *
     * @mbggenerated
     */
    private Long raisedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.create_date
     *
     * @mbggenerated
     */
    private Long createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.ack_date
     *
     * @mbggenerated
     */
    private Long ackDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.recover_date
     *
     * @mbggenerated
     */
    private Long recoverDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.domain_id
     *
     * @mbggenerated
     */
    private Long domainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.enterprise_id
     *
     * @mbggenerated
     */
    private Long enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.signal_id
     *
     * @mbggenerated
     */
    private Long signalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.signal_status
     *
     * @mbggenerated
     */
    private Integer signalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_telesignal_t.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.id
     *
     * @return the value of ids_telesignal_t.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.id
     *
     * @param id the value for ids_telesignal_t.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.station_code
     *
     * @return the value of ids_telesignal_t.station_code
     *
     * @mbggenerated
     */
    public String getStationCode() {
        return stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.station_code
     *
     * @param stationCode the value for ids_telesignal_t.station_code
     *
     * @mbggenerated
     */
    public void setStationCode(String stationCode) {
        this.stationCode = stationCode == null ? null : stationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.station_name
     *
     * @return the value of ids_telesignal_t.station_name
     *
     * @mbggenerated
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.station_name
     *
     * @param stationName the value for ids_telesignal_t.station_name
     *
     * @mbggenerated
     */
    public void setStationName(String stationName) {
        this.stationName = stationName == null ? null : stationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.busi_code
     *
     * @return the value of ids_telesignal_t.busi_code
     *
     * @mbggenerated
     */
    public String getBusiCode() {
        return busiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.busi_code
     *
     * @param busiCode the value for ids_telesignal_t.busi_code
     *
     * @mbggenerated
     */
    public void setBusiCode(String busiCode) {
        this.busiCode = busiCode == null ? null : busiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.busi_name
     *
     * @return the value of ids_telesignal_t.busi_name
     *
     * @mbggenerated
     */
    public String getBusiName() {
        return busiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.busi_name
     *
     * @param busiName the value for ids_telesignal_t.busi_name
     *
     * @mbggenerated
     */
    public void setBusiName(String busiName) {
        this.busiName = busiName == null ? null : busiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.device_type_id
     *
     * @return the value of ids_telesignal_t.device_type_id
     *
     * @mbggenerated
     */
    public Short getDeviceTypeId() {
        return deviceTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.device_type_id
     *
     * @param deviceTypeId the value for ids_telesignal_t.device_type_id
     *
     * @mbggenerated
     */
    public void setDeviceTypeId(Short deviceTypeId) {
        this.deviceTypeId = deviceTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.device_id
     *
     * @return the value of ids_telesignal_t.device_id
     *
     * @mbggenerated
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.device_id
     *
     * @param deviceId the value for ids_telesignal_t.device_id
     *
     * @mbggenerated
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.status_id
     *
     * @return the value of ids_telesignal_t.status_id
     *
     * @mbggenerated
     */
    public Byte getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.status_id
     *
     * @param statusId the value for ids_telesignal_t.status_id
     *
     * @mbggenerated
     */
    public void setStatusId(Byte statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.act_id
     *
     * @return the value of ids_telesignal_t.act_id
     *
     * @mbggenerated
     */
    public Byte getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.act_id
     *
     * @param actId the value for ids_telesignal_t.act_id
     *
     * @mbggenerated
     */
    public void setActId(Byte actId) {
        this.actId = actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.raised_date
     *
     * @return the value of ids_telesignal_t.raised_date
     *
     * @mbggenerated
     */
    public Long getRaisedDate() {
        return raisedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.raised_date
     *
     * @param raisedDate the value for ids_telesignal_t.raised_date
     *
     * @mbggenerated
     */
    public void setRaisedDate(Long raisedDate) {
        this.raisedDate = raisedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.create_date
     *
     * @return the value of ids_telesignal_t.create_date
     *
     * @mbggenerated
     */
    public Long getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.create_date
     *
     * @param createDate the value for ids_telesignal_t.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.ack_date
     *
     * @return the value of ids_telesignal_t.ack_date
     *
     * @mbggenerated
     */
    public Long getAckDate() {
        return ackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.ack_date
     *
     * @param ackDate the value for ids_telesignal_t.ack_date
     *
     * @mbggenerated
     */
    public void setAckDate(Long ackDate) {
        this.ackDate = ackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.recover_date
     *
     * @return the value of ids_telesignal_t.recover_date
     *
     * @mbggenerated
     */
    public Long getRecoverDate() {
        return recoverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.recover_date
     *
     * @param recoverDate the value for ids_telesignal_t.recover_date
     *
     * @mbggenerated
     */
    public void setRecoverDate(Long recoverDate) {
        this.recoverDate = recoverDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.domain_id
     *
     * @return the value of ids_telesignal_t.domain_id
     *
     * @mbggenerated
     */
    public Long getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.domain_id
     *
     * @param domainId the value for ids_telesignal_t.domain_id
     *
     * @mbggenerated
     */
    public void setDomainId(Long domainId) {
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.enterprise_id
     *
     * @return the value of ids_telesignal_t.enterprise_id
     *
     * @mbggenerated
     */
    public Long getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.enterprise_id
     *
     * @param enterpriseId the value for ids_telesignal_t.enterprise_id
     *
     * @mbggenerated
     */
    public void setEnterpriseId(Long enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.signal_id
     *
     * @return the value of ids_telesignal_t.signal_id
     *
     * @mbggenerated
     */
    public Long getSignalId() {
        return signalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.signal_id
     *
     * @param signalId the value for ids_telesignal_t.signal_id
     *
     * @mbggenerated
     */
    public void setSignalId(Long signalId) {
        this.signalId = signalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.name
     *
     * @return the value of ids_telesignal_t.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.name
     *
     * @param name the value for ids_telesignal_t.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.signal_status
     *
     * @return the value of ids_telesignal_t.signal_status
     *
     * @mbggenerated
     */
    public Integer getSignalStatus() {
        return signalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.signal_status
     *
     * @param signalStatus the value for ids_telesignal_t.signal_status
     *
     * @mbggenerated
     */
    public void setSignalStatus(Integer signalStatus) {
        this.signalStatus = signalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_telesignal_t.update_date
     *
     * @return the value of ids_telesignal_t.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_telesignal_t.update_date
     *
     * @param updateDate the value for ids_telesignal_t.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}