package com.interest.ids.common.project.bean.device;

import com.interest.ids.common.project.bean.BaseBean;

import java.math.BigDecimal;

public class TransformerM extends BaseBean {

    private static final long serialVersionUID = 4766746759586570143L;

    private Long enterpriseId;

    private String valid;

    private String busiCode;

    private BigDecimal abU;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_transformer_t.bc_u
     *
     * @mbggenerated
     */
    private BigDecimal bcU;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_transformer_t.ca_u
     *
     * @mbggenerated
     */
    private BigDecimal caU;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_transformer_t.a_u
     *
     * @mbggenerated
     */
    private BigDecimal aU;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_transformer_t.b_u
     *
     * @mbggenerated
     */
    private BigDecimal bU;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_transformer_t.c_u
     *
     * @mbggenerated
     */
    private BigDecimal cU;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_transformer_t.a_i
     *
     * @mbggenerated
     */
    private BigDecimal aI;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_transformer_t.b_i
     *
     * @mbggenerated
     */
    private BigDecimal bI;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_transformer_t.c_i
     *
     * @mbggenerated
     */
    private BigDecimal cI;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_transformer_t.active_power
     *
     * @mbggenerated
     */
    private BigDecimal activePower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_transformer_t.reactive_power
     *
     * @mbggenerated
     */
    private BigDecimal reactivePower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_transformer_t.power_factor
     *
     * @mbggenerated
     */
    private BigDecimal powerFactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ids_transformer_t.elec_freq
     *
     * @mbggenerated
     */
    private BigDecimal elecFreq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_transformer_t.enterprise_id
     *
     * @return the value of ids_transformer_t.enterprise_id
     *
     * @mbggenerated
     */
    public Long getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_transformer_t.enterprise_id
     *
     * @param enterpriseId the value for ids_transformer_t.enterprise_id
     *
     * @mbggenerated
     */
    public void setEnterpriseId(Long enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_transformer_t.valid
     *
     * @return the value of ids_transformer_t.valid
     *
     * @mbggenerated
     */
    public String getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_transformer_t.valid
     *
     * @param valid the value for ids_transformer_t.valid
     *
     * @mbggenerated
     */
    public void setValid(String valid) {
        this.valid = valid == null ? null : valid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_transformer_t.busi_code
     *
     * @return the value of ids_transformer_t.busi_code
     *
     * @mbggenerated
     */
    public String getBusiCode() {
        return busiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_transformer_t.busi_code
     *
     * @param busiCode the value for ids_transformer_t.busi_code
     *
     * @mbggenerated
     */
    public void setBusiCode(String busiCode) {
        this.busiCode = busiCode == null ? null : busiCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_transformer_t.ab_u
     *
     * @return the value of ids_transformer_t.ab_u
     *
     * @mbggenerated
     */
    public BigDecimal getAbU() {
        return abU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_transformer_t.ab_u
     *
     * @param abU the value for ids_transformer_t.ab_u
     *
     * @mbggenerated
     */
    public void setAbU(BigDecimal abU) {
        this.abU = abU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_transformer_t.bc_u
     *
     * @return the value of ids_transformer_t.bc_u
     *
     * @mbggenerated
     */
    public BigDecimal getBcU() {
        return bcU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_transformer_t.bc_u
     *
     * @param bcU the value for ids_transformer_t.bc_u
     *
     * @mbggenerated
     */
    public void setBcU(BigDecimal bcU) {
        this.bcU = bcU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_transformer_t.ca_u
     *
     * @return the value of ids_transformer_t.ca_u
     *
     * @mbggenerated
     */
    public BigDecimal getCaU() {
        return caU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_transformer_t.ca_u
     *
     * @param caU the value for ids_transformer_t.ca_u
     *
     * @mbggenerated
     */
    public void setCaU(BigDecimal caU) {
        this.caU = caU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_transformer_t.a_u
     *
     * @return the value of ids_transformer_t.a_u
     *
     * @mbggenerated
     */
    public BigDecimal getaU() {
        return aU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_transformer_t.a_u
     *
     * @param aU the value for ids_transformer_t.a_u
     *
     * @mbggenerated
     */
    public void setaU(BigDecimal aU) {
        this.aU = aU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_transformer_t.b_u
     *
     * @return the value of ids_transformer_t.b_u
     *
     * @mbggenerated
     */
    public BigDecimal getbU() {
        return bU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_transformer_t.b_u
     *
     * @param bU the value for ids_transformer_t.b_u
     *
     * @mbggenerated
     */
    public void setbU(BigDecimal bU) {
        this.bU = bU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_transformer_t.c_u
     *
     * @return the value of ids_transformer_t.c_u
     *
     * @mbggenerated
     */
    public BigDecimal getcU() {
        return cU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_transformer_t.c_u
     *
     * @param cU the value for ids_transformer_t.c_u
     *
     * @mbggenerated
     */
    public void setcU(BigDecimal cU) {
        this.cU = cU;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_transformer_t.a_i
     *
     * @return the value of ids_transformer_t.a_i
     *
     * @mbggenerated
     */
    public BigDecimal getaI() {
        return aI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_transformer_t.a_i
     *
     * @param aI the value for ids_transformer_t.a_i
     *
     * @mbggenerated
     */
    public void setaI(BigDecimal aI) {
        this.aI = aI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_transformer_t.b_i
     *
     * @return the value of ids_transformer_t.b_i
     *
     * @mbggenerated
     */
    public BigDecimal getbI() {
        return bI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_transformer_t.b_i
     *
     * @param bI the value for ids_transformer_t.b_i
     *
     * @mbggenerated
     */
    public void setbI(BigDecimal bI) {
        this.bI = bI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_transformer_t.c_i
     *
     * @return the value of ids_transformer_t.c_i
     *
     * @mbggenerated
     */
    public BigDecimal getcI() {
        return cI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_transformer_t.c_i
     *
     * @param cI the value for ids_transformer_t.c_i
     *
     * @mbggenerated
     */
    public void setcI(BigDecimal cI) {
        this.cI = cI;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_transformer_t.active_power
     *
     * @return the value of ids_transformer_t.active_power
     *
     * @mbggenerated
     */
    public BigDecimal getActivePower() {
        return activePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_transformer_t.active_power
     *
     * @param activePower the value for ids_transformer_t.active_power
     *
     * @mbggenerated
     */
    public void setActivePower(BigDecimal activePower) {
        this.activePower = activePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_transformer_t.reactive_power
     *
     * @return the value of ids_transformer_t.reactive_power
     *
     * @mbggenerated
     */
    public BigDecimal getReactivePower() {
        return reactivePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_transformer_t.reactive_power
     *
     * @param reactivePower the value for ids_transformer_t.reactive_power
     *
     * @mbggenerated
     */
    public void setReactivePower(BigDecimal reactivePower) {
        this.reactivePower = reactivePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_transformer_t.power_factor
     *
     * @return the value of ids_transformer_t.power_factor
     *
     * @mbggenerated
     */
    public BigDecimal getPowerFactor() {
        return powerFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_transformer_t.power_factor
     *
     * @param powerFactor the value for ids_transformer_t.power_factor
     *
     * @mbggenerated
     */
    public void setPowerFactor(BigDecimal powerFactor) {
        this.powerFactor = powerFactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ids_transformer_t.elec_freq
     *
     * @return the value of ids_transformer_t.elec_freq
     *
     * @mbggenerated
     */
    public BigDecimal getElecFreq() {
        return elecFreq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ids_transformer_t.elec_freq
     *
     * @param elecFreq the value for ids_transformer_t.elec_freq
     *
     * @mbggenerated
     */
    public void setElecFreq(BigDecimal elecFreq) {
        this.elecFreq = elecFreq;
    }
}